source 'https://rubygems.org'

gem 'rails', '4.2.3'

gem 'bootstrap-sass'
gem 'carrierwave'
gem 'coffee-rails', '~> 4.1.0'
gem 'devise'
gem 'devise-i18n'
gem 'globalize', '~> 4.0.2'
gem 'haml-rails'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'jquery-turbolinks'
gem 'mini_magick'
gem 'rails-i18n'
gem 'sass-rails', '~> 5.0'
gem 'sidekiq'
gem 'sqlite3'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
gem 'unicorn'
gem 'will_paginate'

group :development, :test do
  gem 'byebug'
  gem 'capybara'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'rspec-rails'
  gem 'simplecov'
  gem 'spring'
  gem 'web-console', '~> 2.0'
end

