Category.create([
  { name: 'Action and Adventure' },
  { name: 'Anthologies' },
  { name: 'Art' },
  { name: 'Autobiographies' },
  { name: 'Biographies' },
  { name: 'Children' },
  { name: 'Comics' },
  { name: 'Cookbooks' },
  { name: 'Diaries' },
  { name: 'Dictionaries' },
  { name: 'Drama' },
  { name: 'Encyclopedias' },
  { name: 'Fantasy' },
  { name: 'Guide' },
  { name: 'History' },
  { name: 'Horror' },
  { name: 'Journals' },
  { name: 'Math' },
  { name: 'Mystery' },
  { name: 'Poetry' },
  { name: 'Prayer books' },
  { name: 'Religious' },
  { name: 'Romance' },
  { name: 'Satire' },
  { name: 'Science fiction' },
  { name: 'Science' },
  { name: 'Self help' },
  { name: 'Series' },
  { name: 'Travel' },
  { name: 'Trilogies' }
])
